### ISSUE TITLE
Code archeology notes

### ISSUE THREAD

**Issue by hugovk** [termcolor/termcolor#16]
# Notes on reconstructing history

Because there's no record of this project's code repo, I thought it would be nevertheless be good to have some sort of history.

I downloaded the old sdists from https://pypi.org/project/termcolor/#history to reconstruct it.

This repo had started from an initial commit of the latest 1.1.0 sdist.

I followed https://stackoverflow.com/a/59548348/724176 to add new commits before the current repo's initial commit.

For each commit, I took the sdist contents, and made a single commit:

```
Version X.Y.Z

Co-authored-by: Konstantin Lepa <konstantin.lepa@gmail.com>
```

and committed like `gc --date="2011-01-13T18:45:33.979856Z"`, using the `upload_time_iso_8601` of the release from https://pypi.org/pypi/termcolor/json

---

Because this rewrote the Git history of this repo, if you have a clone, I suggest deleting and re-cloning. I'm doing this now to get a clean starting point to continue and won't be rewriting history once this is sorted :)

---

First pass, I had this locally:

![image](https://user-images.githubusercontent.com/1324225/189116474-2f77c829-397e-4571-b05c-d9651502d2f9.png)

But this on [GitHub](https://github.com/termcolor/termcolor/commits/main):

![image](https://user-images.githubusercontent.com/1324225/189116728-fc357d6a-6fd8-494c-b2c1-859e1a43b6de.png)

Seems there's also a difference between "author date" and "commit date":

https://github.com/orgs/community/discussions/22695#discussioncomment-3237743

So I re-filtered with their suggestion:

```sh
git filter-branch --env-filter 'export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"'
git push -f
```

And it now looks good locally:

![image](https://user-images.githubusercontent.com/1324225/189116886-b556988e-ba69-4f71-914c-7dc0eb2d5c4a.png)

And on GitHub:

![image](https://user-images.githubusercontent.com/1324225/189116936-dc3dd0c2-5d80-4cb9-9d19-42d06b2e0247.png)

...

![image](https://user-images.githubusercontent.com/1324225/189117128-217b6130-e791-4f0f-92c6-acb9986ed8e6.png)
![image](https://user-images.githubusercontent.com/1324225/189117168-ce5c9c65-c91b-41f2-a6aa-43790f14be1d.png)

**Comment by hugovk** [comment]
Created tags from those commits like:

```sh
git tag -a 0.1   -m "Release 0.1"   9fa47eadc3ce76e3dc15115d420e9575baab6601
git tag -a 0.1.1 -m "Release 0.1.1" ba42abd77069a26224460e74baf9ba567f1facd8
git tag -a 0.1.2 -m "Release 0.1.2" 404c8ef7ba3ea89f08740a0c1a7e4beec988cd27
git tag -a 0.2   -m "Release 0.2"   2fcb6da9c402a6528af560d4c7b9193784f603e4
git tag -a 1.0.0 -m "Release 1.0.0" f152f6d40f8be53af513a4919ead8de915aaf79c
git tag -a 1.0.1 -m "Release 1.0.1" 85c8fa64c51dc5906231c23e5625643184e08f22
git tag -a 1.1.0 -m "Release 1.1.0" fce9d9a6fd97b659282b3e893500fe80cbeac6e2

Updated dates using https://stackoverflow.com/a/25939259/724176 :

```sh
git tag -l | while read -r tag ; do COMMIT_HASH=$(git rev-list -1 $tag) && GIT_COMMITTER_DATE="$(git show $COMMIT_HASH --format=%aD | head -1)" git tag -a -f $tag -m"$tag" $COMMIT_HASH ; done
git push --tags
```

And created GitHub releases from those tags.

**Comment by hugovk** [comment]
Okay, all done here!

Ping @CozyDoomer, @gururajrkatti, @jdkloe, @jdufresne, @mpenning, @tmetzl:

As a one-off, history has been rewritten in this repo, you may want to delete/re-create your clones or branches.

Thanks!

**Comment by ofek** [comment]
Interesting read, good job!
