### ISSUE TITLE
Respect NO_COLOR and FORCE_COLOR

### ISSUE THREAD

**Issue by hugovk** [termcolor/termcolor#2]
* https://no-color.org/
* https://github.com/pytest-dev/pytest/issues/7464
* https://github.com/pytest-dev/pytest/pull/7466
* [x] https://github.com/termcolor/termcolor/pull/7
* [ ] https://github.com/termcolor/termcolor/pull/25

**Comment by blueyed** [comment]
`FORCE_COLOR` is not really a (community) standard.

From all the projects (apart from pytest where you've added it) I've checked out locally only https://github.com/qix-/better-exceptions uses it, but requires it to be "1" then - unlike pytest where any value forces color (similar to `NO_COLOR`).
(Other projects use specific vars (`ANSIBLE_FORCE_COLOR`, `VAGRANT_FORCE_COLOR`, …), similar to pytest using `PY_COLORS`.)

**Comment by hugovk** [comment]
Yeah, `FORCE_COLOR` definitely isn't anywhere as widespread as `NO_COLOR`, but I think `FORCE_COLOR` is a useful addition (actually, it won't be useful here until there's also tty detection).

There's also a PR (nearly one year old!) for Colorama (https://github.com/tartley/colorama/pull/230) that adds both, and checks for presence, regardless of its value. I think that makes sense, to use the same way of checking for `FORCE_COLOR` as `NO_COLOR`.

Thanks!

**Comment by tomwatson1024** [comment]
AIUI this change means that `termcolor` _always_ respects `NO_COLOR` - but what if the user doesn't want to use that environment variable? In particular, termcolor now has different behaviour based on the user's environment, which wasn't the case before.

I ask because I maintain a (proprietary) library using termcolor that allows users to:

- explicitly enable color;
- explicitly disable color;
- allow color autodetection, using `NO_COLOR`.

With this change, I can no longer explicitly enable color (without patching `os.environ`)!

**Comment by hugovk** [comment]
Yes, that's correct, `NO_COLOR` overrides termcolor (and will also override `FORCE_COLOR` when it's added).

The idea is the person running a command-line tool has an easy way to disable colour output across all tools, and they may not be able to change the tool code itself.

> Perhaps `termcolor.colored` could take a keyword argument controlling use of `NO_COLOR`?

Then we have a bit of an "conflict":

* dev wants colour, so uses `colored`
* user doesn't want colour, so uses `FORCE_COLOR` to override `colored`
* dev wants colour, so uses `colored(ignore_force_color=True)` to override `FORCE_COLOR` that overrides `colored`
* next step: `REALLY_FORCE_COLOR`? ;)

> With this change, I can no longer explicitly enable color (without patching `os.environ`)!

Yeah, that might actually be a reasonable way to do it: if you really don't want `NO_COLOR`, just unset it.

```python
import os
import termcolor

del os.environ["NO_COLOR"]

termcolor.cprint("hi", "green")
```

**Comment by tomwatson1024** [comment]
I think it's a good idea to respect `NO_COLOR` _by default_, as it enables devs who don't want to think too much about color support to have the "right thing" happen, without writing any extra code.

However, I do think there's value in allowing the developer full control over color _if they want it_. For example:

- an application that implements its own color selection logic, as in my comment above. In this case the developer is (hopefully) providing means for the user to disable color and, if not, well that's on them - they've opted in to the fine-grained control!
- colored text that is not directly written directly to the user's terminal - instead it's saved to a file for later use, or compared to output in e.g. unit test.

I'm sure there are other cases, too, where it's useful for coloration to be "pure", in the sense that its behaviour is consistent regardless of the user's environment.

> "Make simple things simple, and complex things possible"

That said, I appreciate that termcolor is ultimately open-source and provided for free! If you prefer to go a different route, that's entirely your perogative.

**Comment by hugovk** [comment]
PR https://github.com/termcolor/termcolor/pull/25 adds tty detection and support for the `FORCE_COLOR` env var.

**Comment by hugovk** [comment]
Please see PR https://github.com/termcolor/termcolor/pull/38 to add parameters to override the environment variables.
