### ISSUE TITLE
No longer works in PyCharm console

### ISSUE THREAD

**Issue by Nyaaa** [termcolor/termcolor#30]
In reference to #28 

The issue: termcolor no longer colorizes text in PyCharm.
The issue affects Python Console:

<img width="607" alt="Screenshot 2022-11-21 103250" src="https://user-images.githubusercontent.com/1457047/202992757-544a5206-9450-40d1-8751-d2e3cdf2cd2c.png">
<img width="616" alt="Screenshot 2022-11-21 103447" src="https://user-images.githubusercontent.com/1457047/202992769-d1ebf34b-e6e5-486b-bb29-ed04eaf4a612.png">

 It also affects the console that PyCharm outputs to when you use the Run button:

<img width="550" alt="Screenshot 2022-11-21 102823" src="https://user-images.githubusercontent.com/1457047/202993044-8fedaccd-abcb-4f27-ac53-8855507e6567.png">
<img width="550" alt="Screenshot 2022-11-21 102955" src="https://user-images.githubusercontent.com/1457047/202993058-cf0684dd-04e0-4588-8537-65d70512634a.png">

- Version 2.0.1 works fine
- Versions 2.1.0 and 2.1.1 don't work on their own and require a workaround `os.environ["FORCE_COLOR"] = "1"`

**Comment by hugovk** [comment]
Here's the PyCharm bug report to upvote: [youtrack.jetbrains.com/issue/PY-43798](https://youtrack.jetbrains.com/issue/PY-43798)

Re: https://github.com/termcolor/termcolor/issues/28#issuecomment-1321244497)
