### ISSUE TITLE
Black text color

### ISSUE THREAD

**Issue by 4l1fe** [termcolor/termcolor#31]
Could you explain how to make text black, i see no constant for it?

At the moment i do so `on_blue = lambda text: colored(colorama.Fore.BLACK+text, on_color='on_blue', attrs=['bold'])`

**Comment by hugovk** [comment]
The `gray` constant really shows up as black.

https://github.com/termcolor/termcolor/pull/32 will add `black` and `on_black` constants which will be the same colour as `grey` and `on_grey`. I'll release that in the next few days.

In the meantime, you can do something like:

```pycon
>>> from termcolor import cprint
>>> cprint("hello", "grey", "on_blue")
```

<img width="275" alt="image" src="https://user-images.githubusercontent.com/1324225/204652477-558b1af7-fc03-4fe4-b6f8-cdd9942250f8.png">

**Comment by 4l1fe** [comment]
Yep, i see no difference. Thank you!
