### ISSUE TITLE
feature request: force colours

### ISSUE THREAD

**Issue by sinux-l5d** [termcolor/termcolor#33]
Hi,

I have a special case where I pipe my script using termcolor to `fzf --ansi` to keep colours. But it seems that `_can_do_colour()` wants stdout to be interactive, so this is not possible for now.

Would it be possible to init the module with forced colours?

**Comment by hugovk** [comment]
It's possible by setting the `FORCE_COLOR` environment variable. Is that suitable for you?

I'm considering also adding `force_color` and `no_color` parameters, which could help https://github.com/termcolor/termcolor/issues/28#issuecomment-1328934104 and  https://github.com/termcolor/termcolor/issues/2#issuecomment-1287010438 respectively.

**Comment by sinux-l5d** [comment]
Works like a charm!
But indeed a parameter would be more suitable in some cases, when you want to pass an option to a script instead of prefixing it with a shell variable.
That will be ok in my case, thanks :D

**Comment by hugovk** [comment]
Please see PR https://github.com/termcolor/termcolor/pull/38 to add parameters to override the environment variables.

**Comment by GergelyKalmar** [comment]
This would be very useful for me as well – in [pytest-logikal](https://docs.logikal.io/pytest-logikal/latest/) I'm running some checks in a (non-interactive) subprocess but I'd still like to have the output be colored when collecting the results. Would there be any chance to merge PR #38 and release it?

**Comment by hugovk** [comment]
Yes, I'll merge it now and release it in the next day or two, hopefully we can include #44 as well.

**Comment by GergelyKalmar** [comment]
That would be totally awesome! Thank you very much.

**Comment by hugovk** [comment]
Released: 

https://pypi.org/project/termcolor/2.3.0/ 

https://github.com/termcolor/termcolor/releases/tag/2.3.0

🚀

**Comment by doniks** [comment]
are these options documented somewhere?

**Comment by hugovk** [comment]
They're not, and they should be. Thanks for the prompt, I'll open an issue to make sure they're added.

**Comment by hugovk** [comment]
Please see PR https://github.com/termcolor/termcolor/pull/60.
