### ISSUE TITLE
Doesn't work in GitHub Actions

### ISSUE THREAD

**Issue by orome** [termcolor/termcolor#57]
In GitHub Actions I see no color output (though attributes like bold are working).

**Comment by hugovk** [comment]
GitHub Actions is not a tty:

* https://github.com/actions/runner/issues/241

So you need to set `FORCE_COLOR`, for example:

https://github.com/termcolor/termcolor/blob/fd585675cd629052252063f11488a5007e01d8fd/.github/workflows/test.yml#L5-L6

**Comment by orome** [comment]
@hugovk Perfect! Thanks! (Any idea why pytest shows color even w/o this?)

**Comment by hugovk** [comment]
pytest doesn't show colour by default in GitHub Actions:

<img width="858" alt="image" src="https://github.com/termcolor/termcolor/assets/1324225/41333f66-0727-4bde-a1d1-d471773551e7">

https://github.com/hugovk/test/actions/runs/6644087974/job/18052478766

With `FORCE_COLOR: 1`:

<img width="853" alt="image" src="https://github.com/termcolor/termcolor/assets/1324225/a0cc5352-1b29-4ef7-9efc-5a83461a141a">

https://github.com/hugovk/test/actions/runs/6644094322/job/18052503350

You probably have colour enabled via a config file or CLI option.

**Comment by orome** [comment]
@hugovk Yes, correct. So pytest is responding to that flag by setting doing what? (In other words, is there something I could do in my own code to have the same effect, rather than using the Action's env variable?)

**Comment by hugovk** [comment]
I don't know what pytest is doing in your codebase: it is either reading an environment variable, or is reading a config value.

termcolor can also read the `FORCE_COLOR` env var, or you can pass `force_color=True` to termcolor's `colored` or `cprint`: https://github.com/termcolor/termcolor/pull/38

**Comment by orome** [comment]
@hugovk Got it! That's what I was looking for. Thanks!
