### ISSUE TITLE
Apache/mod_wsgi log object is not associated with a file descriptor.

### ISSUE THREAD

**Issue by hrlien** [termcolor/termcolor#63]
Apache/mod_wsgi log object is not associated with a file descriptor.
When upgrading from 2.3.0 to 2.4.0 in my Django project
Error probably due to change in isatty
```python
    # Then check system:
    if os.environ.get("TERM") == "dumb":
        return False
    if not hasattr(sys.stdout, "fileno"):
        return False
    try:
        return os.isatty(sys.stdout.fileno()) …
    except io.UnsupportedOperation:
        return sys.stdout.isatty()
```

**Comment by hugovk** [comment]
Please can you share a full traceback?

Did you have colour output before?

Is using an override an option for you? https://github.com/termcolor/termcolor#overrides
