### ISSUE TITLE
The "light_" colors don't work.

### ISSUE THREAD

**Issue by jmadison222** [termcolor/termcolor#64]
The "light_" values don't work, but the regular values do.  Don't worry that it's printing control characters for green, it works fine on the terminal.  But the use of "light_magenta" fails as shown:
```pycon
Python 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 23:51:54)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from termcolor import colored
>>> colored('Works','green')
'\x1b[32mWorks\x1b[0m'
>>> colored('Fails','light_magenta')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/app/anaconda_3.6/lib/python3.6/site-packages/termcolor.py", line 105, in colored
    text = fmt_str % (COLORS[color], text)
KeyError: 'light_magenta'
```
It's odd because you code clearly shows light_magenta all over the place.  I have the same success with other base colors ('white', etc.), and have the same trouble with other light_* colors.

My $TERM is set to "xterm".

Thoughts?

**Comment by jmadison222** [comment]
I saw the other issue related to this.  But it's from back in January.  My current version is this:

    termcolor==1.1.0

Not sure if that matters,

**Comment by hugovk** [comment]
It matters, the light colours were added in 2.2.0:

https://github.com/termcolor/termcolor/releases/tag/2.2.0

**Comment by jmadison222** [comment]
Ah, perfect.  Thanks!
