### ISSUE TITLE
Text doesn't have strike attribute when using 'light_grey' as color

### ISSUE THREAD

**Issue by DariusArgent** [termcolor/termcolor#79]
![bug](https://github.com/termcolor/termcolor/assets/13587952/1137c359-a697-4043-971e-15e57a0005f8)
Every other color seems to be working as intended
EDIT: It seems that the bold attribute on the first text is making the issue, otherwise it's fine without it

**Comment by hugovk** [comment]
I think this depends on terminal support.

Running `python -c "from termcolor import colored; print(colored('Test', 'grey', attrs=['strike']))"` with iTerm on macOS, I get:

<img width="659" alt="image" src="https://github.com/termcolor/termcolor/assets/1324225/3d10fe68-83f3-4145-b2d4-d4118adf9372">

The grey doesn't really show up on dark background, if I highlight it I can see the strikethrough:

<img width="674" alt="image" src="https://github.com/termcolor/termcolor/assets/1324225/9780e77f-37fb-46cb-880f-2aee1d00cae6">

However, if I use Terminal, I don't see any strikethrough:

<img width="566" alt="image" src="https://github.com/termcolor/termcolor/assets/1324225/5db2a732-b800-4fce-a6b9-e26afa1c5bd7">

What OS, Python and terminal are you using?

You could try using the ANSI codes directly, for example:

```python
print("\033[9m" + "hi" + "\033[0m")  # strike + hi + reset
print("\033[9m" + "\033[92m" + "hi" + "\033[0m")  # # strike + green + hi + reset
```

Do you get similar results?
