### ISSUE TITLE
Type hinting?

### ISSUE THREAD

**Issue by FYI-PSA** [termcolor/termcolor#85]
Hello.
This library is a bit difficult to use with type hints.
Any way to use the types defined inside the code?
e.g.:
`Pyright : Argument of type "str" cannot be assigned to parameter "color" of type "Color | None"`
 - When trying to use a colored output in a function

**Comment by hugovk** [comment]
Please can you show the full warning? Which line is it applying to?

See also https://github.com/termcolor/termcolor/issues/62.
